### ISSUE TITLE
New mouse hover

### ISSUE THREAD

**Issue by camilasan** [monopolies/monopolies.net#1]
Hi @jancborchardt 

Suggestion:

![suggestion2](https://user-images.githubusercontent.com/241266/50523482-ab01ad80-0ad0-11e9-80f8-a1e59652a1c0.png)
![suggesiton](https://user-images.githubusercontent.com/241266/50523484-ab01ad80-0ad0-11e9-869e-e8bd2e3cb565.png)

Changes the mouse hover to an x and increases font weight of the real slogan.

p.s: could you add me to the org so I can push my branch?

Thanks!

**Comment by jancborchardt** [comment]
Looks sooo much better and obvious, thanks a lot @camilasan! :)

**Comment by jancborchardt** [comment]
Fixed via #2 and looks muuuch better indeed! :rocket:
